server:
  port: ${PORT:8080}
spring:
  application:
    name: velazco-backend
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
  config:
    import: optional:file:.env[.properties]
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
jwt:
  secret: ${JWT_SECRET}
storage:
  upload-dir: ${RAILWAY_VOLUME_MOUNT_PATH:/app/uploads}
app:
  security:
    jwt:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER:${PGUSER}}
    password: ${POSTGRES_PASSWORD:${PGPASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
base:
  url: ${BASE_URL}
frontend:
  url: ${FRONTEND_URL}
