spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/velazco-back
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-local-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-local-google-client-secret}

storage:
  upload-dir: uploads

base:
  url: http://localhost:8080
frontend:
  url: http://localhost:5173

# Esta configuración local solo se activa con SPRING_PROFILES_ACTIVE=local
